### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by chburger** [ExaChem/exachem#2]
Thanks alot for providing the code: I have a problem to compile it, however. Do you have some advice? GCROOTPATH is not defined.

~/exachem/build> CC=icx CXX=icpx FC=mpiifort cmake -DUSE_CUDA=ON -DLINALG_VENDOR=IntelMKL -DCMAKE_INSTALL_PREFIX=$HOME/nwchemx  -DMODULES="CC" ..
-- The C compiler identification is IntelLLVM 2024.0.2
-- The CXX compiler identification is IntelLLVM 2024.0.2
-- The Fortran compiler identification is Intel 2021.1.0.20231117
....

CMake Error at build/_deps/cmakebuild-src/cmake/macros/BuildCMSBModule.cmake:69 (message):
  GCCROOT cmake option not set when using clang compilers.  Please set a
  valid path to the GCC installation.
Call Stack (most recent call first):
  build/_deps/cmakebuild-src/CMakeLists.txt:31 (build_cmsb_module)

-- Configuring incomplete, errors occurred!

**Comment by ajaypanyala** [comment]
Intel compilers for CUDA builds of exachem is not tested. It would be safer to use GCC (version >= 9.x) for your build. `CC=gcc CXX=g++ FC=gfortran cmake -DUSE_CUDA=ON -DLINALG_VENDOR=IntelMKL -DCMAKE_INSTALL_PREFIX=$HOME/nwchemx -DMODULES="CC" ..`
